
--- DROP TABLE IF EXISTS Test;
--- CREATE TYPE Loan_Status AS ENUM ('On Loan', 'In Library', 'Overdue');


CREATE TABLE Test (
  Id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  String VARCHAR(100) NOT NULL DEFAULT 'NULL',
  Loan_Status Loan_Status
);

INSERT INTO Test VALUES (1, 'Hello', 'Overdue');
INSERT INTO Test(String, Loan_Status) VALUES ('Hello2', 'Overdue');

SELECT * FROM Test;
