
--- DROP TABLE IF EXISTS Test;
--- CREATE TYPE Loan_Status AS ENUM ('On Loan', 'In Library', 'Overdue');


CREATE TABLE Test (
  Id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  String VARCHAR(100) NOT NULL DEFAULT 'NULL',
  Loan_Status Loan_Status
);

INSERT INTO Test VALUES (1, 'Hello', 'Overdue');
INSERT INTO Test(String, Loan_Status) VALUES ('Hello2', 'Overdue');

SELECT * FROM Test;

---- Example records in each Table

INSERT INTO Titles VALUES ('978-3-16-148410-0', 'Harry Potter', 'JK Rowling', 'Fantasy');
INSERT INTO Books(Title_ISBN, On_Shelf) VALUES ('978-3-16-148410-0', FALSE);

INSERT INTO Users(Forename, Surname) VALUES ('Bob', 'Bloggs');
INSERT INTO Users(Forename, Surname) VALUES ('Joe', 'Bloggs');

INSERT INTO Loans(User_ID, Book_ID, Loan_Date, Return_Date, Loan_Status) VALUES (1, 1, '12/11/2018', '1/12/2018', 'On Loan');


SELECT * FROM Users;
